# Generated by Django 3.0.6 on 2020-05-09 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200, null=True)),
                ('type', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('num', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
