# Generated by Django 3.0.6 on 2020-05-11 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('img', models.CharField(max_length=200, null=True)),
                ('video', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('params', models.CharField(max_length=400)),
                ('flows', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
