# Generated by Django 3.0.6 on 2020-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cid',
            field=models.IntegerField(null=True),
        ),
    ]
