# Generated by Django 3.0.6 on 2020-05-11 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='careate_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
