# Generated by Django 3.0.6 on 2020-05-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category_careate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cid',
        ),
    ]
