# Generated by Django 3.0.6 on 2020-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_user_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='cid',
            field=models.IntegerField(null=True),
        ),
    ]
