# Generated by Django 3.0.6 on 2020-05-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_goods_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
